[package]
name = "lisb_os"
version = "0.1.0"
edition = "2018"
authors = ["Gabriel Lisboa <gabriellisboa.rx@gmail.com>"]

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
