[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
panic-abort-tests = true

[build]
target = "x86_64-lisb_os.json"

[target.'x86_64-lisb_os']
runner = "bootimage runner"
